name: Model Retraining

on:
  # Trigger the workflow to run every week
  schedule:
    - cron: '0 0 * * 0' # Every sunday at midnight (UTC)
  # Trigger the workflow when a new dataset or change is pushed to the repository
  push:
    branches:
      - master # Run on any push to the main branch (mine's called master)

jobs:
  retrain:
    runs-on: ubuntu-latest # Use Ubuntu as the environment

    # Add environment variables
    env:
      AWS_ACCESS_KEY_iD: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-2'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' 

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Debug - Check if AWS credentials are set
      - name: Check AWS Credentials
        run: |
          echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"
          echo "AWS Secret Access Key: $AWS_SECRET_ACCESS_KEY"
          echo "AWS Default Region: $AWS_DEFAULT_REGION"

      # Step 4: Run the training script
      - name: Run retraining.py
        run: |
          python retraining.py 
